source 'https://github.com/CocoaPods/Specs.git'
pod 'HexColors', :git => 'https://github.com/mRs-/HexColors.git'
pod 'PPTopMostController', :git => 'https://github.com/donileo/PPTopMostController.git'
pod 'RMessage', :path => '../' 
